export default class NavigationCommonConstant {

  /** 填满空间  */
  static readonly FULL_ALL_SPACE: string = "100%"

  /** 返回图标的大小  */
  static readonly BACK_IMAGE_SIZE: number = 24

  /** 返回图标距离左侧屏幕的间距  */
  static readonly BACK_IMAGE_LEFT_MARGIN: number = 15

  /** 中间内容距离两侧的间距  */
  static readonly CONTENT_HORIZONTAL_SPACE: number = 10

  /** 右侧功能按钮的事件点击区域宽度，高度跟随内容的高度  */
  static readonly RIGHT_IMAGE_BOX_WIDTH: number = 45

  /** 右侧功能按钮距离右侧屏幕的间距  */
  static readonly RIGHT_IMAGE_ON_SCREEN_RIGHT_MARGIN: number = 8.5

  /** 内容的高度  */
  static readonly CONTENT_HEIGHT: number = 40

}