export class ColorConst{
  public static readonly MAIN_TEXT = 0xFF222222;
  public static readonly TEXT_DARK = 0xFF666666;
  public static readonly TEXT_LIGHT =  0xFF999999;
  // 页面中分割线颜色
  public static readonly SPLIT_LINE =  0xFFE8E8E8;
  // 所有页面背景颜色
  public static readonly DEFAULT_BG = 0xFFf1f2f3;
  // 收藏颜色
  public static readonly COLLECT = 0xFFFA8072;
  // 金色
  public static readonly GOLD =  0xFFFFD700;
  public static readonly TEXT_TAB_INACTIVE =  0xFFE6E6FA;

  public static readonly WX_GREEN = 0xFF3CB371;
  public static readonly ICON_GRAY = 0xFFE0E0E0;
  public static readonly GUIDE_BG = 0xFFF8F8F8;

}